/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wu_safe_smart_jni_JniCount */

#ifndef _Included_com_wu_safe_smart_jni_JniCount
#define _Included_com_wu_safe_smart_jni_JniCount
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wu_safe_smart_jni_JniCount
 * Method:    getFromNative
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_wu_safe_smart_jni_JniCount_getFromNative
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
