/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

/* Header for class lab_sodino_jnitest_MainActivity */

#ifndef _Included_com_smart_jni_Count
#define _Included_com_smart_jni_Count
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class: lab_sodino_jnitest_MainActivity
 * Method: getStringFromNative
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_smart_jni_JniCount_getFromNative
  (JNIEnv * env, jobject jObj){
      return env->NewStringUTF("this is jni");
  }

#ifdef __cplusplus
}
#endif
#endif
